name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: antegral/text-generation-webui:B$(date +%s)
          cache-from: type=gha
          cache-to: type=gha,mode=max
